version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.7

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}

      - run: echo $SLACK_TOKEN > secret

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            pipenv install

      - run:
          name: update calendar
          when: always
          command: |
            pipenv run python tnct-info/event.py tnct-calendar.ics
            git config --global user.email arata04962@gmail.com
            git config --global user.name arata-nvm
            git add out/tnct-calendar.ics
            git commit -m "[ci skip] Update tnct-calendar.ics" --allow-empty
            git push -f origin master

      - run:
          name: update notice
          when: always
          command: |
            pipenv run python tnct-info/notice.py atom.xml

      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"

workflows:
  version: 2
  normal_workflow:
    jobs:
      - build
  schedule_workflow:
    triggers:
      - schedule:
          cron: "0 22 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
